// Prepares a throwaway Astro project (.yt-companion/) from the bundled theme + the user's overrides,
// then drives Astro's programmatic API against it.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { loadConfig } from './config.js';
import { copyDir, log } from './util.js';

const require = createRequire(import.meta.url);
export const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
export const THEME_DIR = path.join(PKG_ROOT, 'theme');
export const WORK_DIRNAME = '.yt-companion';

function astroNodeModules() {
  // Works for local clones, `npm link`, global installs, and hoisted installs.
  const pkg = require.resolve('astro/package.json');
  return path.dirname(path.dirname(pkg));
}

export async function importAstro() {
  return import(pathToFileURL(require.resolve('astro')).href);
}

export function prepare(siteRoot) {
  const cfg = loadConfig(siteRoot);
  const work = path.join(siteRoot, WORK_DIRNAME);

  // Fresh src/public each run so deleted overrides don't linger; keep Astro's cache.
  for (const d of ['src', 'public']) fs.rmSync(path.join(work, d), { recursive: true, force: true });
  fs.mkdirSync(work, { recursive: true });

  copyDir(THEME_DIR, work, { filter: (s) => !path.relative(THEME_DIR, s).split(path.sep).includes('node_modules') });

  // Theme overrides: anything in <site>/theme mirrors the theme layout (theme/src/components/Footer.astro, ...).
  const overrides = path.join(siteRoot, 'theme');
  if (fs.existsSync(overrides)) {
    const n = countFiles(overrides);
    if (n) log.info(`Applying ${n} theme override file(s) from theme/`);
    copyDir(overrides, work, { filter: (s) => !/README\.md$/i.test(s) });
  }
  // User static assets (favicon, images, ads.txt, CNAME...)
  copyDir(path.join(siteRoot, 'public'), path.join(work, 'public'));

  const generated = {
    ...cfg,
    __contentDir: path.join(siteRoot, 'content').split(path.sep).join('/'),
    __builtAt: new Date().toISOString(),
  };
  fs.mkdirSync(path.join(work, 'src/generated'), { recursive: true });
  fs.writeFileSync(
    path.join(work, 'src/generated/site-config.mjs'),
    `// Generated by yt-companion from config.yaml — do not edit.\nexport default ${JSON.stringify(generated, null, 2)};\n`,
  );

  const nm = path.join(work, 'node_modules');
  try {
    fs.rmSync(nm, { recursive: true, force: true });
  } catch {}
  fs.symlinkSync(astroNodeModules(), nm, 'junction');

  for (const d of ['videos', 'posts', 'playlists']) fs.mkdirSync(path.join(siteRoot, 'content', d), { recursive: true });
  return { cfg, work };
}

function countFiles(dir) {
  let n = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    n += e.isDirectory() ? countFiles(path.join(dir, e.name)) : e.name.startsWith('.') || /^readme\.md$/i.test(e.name) ? 0 : 1;
  }
  return n;
}
